import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by IIS on 25.02.2016.
 */
public class Cinema {
    public static void main(String[] args) throws SQLException {
        try (Connection connection = DriverManager.getConnection("jdbc:derby:CinemaDB;create=true")) {
            try (PreparedStatement create1 = connection.prepareStatement("create table HALLS(num int not null primary key,nrows int not null)")) {
                create1.execute();
            }
            try (PreparedStatement create2 = connection.prepareStatement("create table SEANCES(ID int not null generated by default as identity (start with 100)primary key," +
                    "stime varchar(5) not null,film varchar(100) not null,hall int not null,age int not null,price int not null,foreign key(hall)references HALLS(num))")) {
                create2.execute();
            }
            try (PreparedStatement create3 = connection.prepareStatement("create table HROWS(hall int not null,row int not null,seats int not null,foreign key(hall) references HALLS(num))")) {
                create3.execute();
            }
            try (PreparedStatement create4 = connection.prepareStatement("create table RESERVATIONS(userId varchar(100) not null,row int not null,seat int not null,seance int not null," +
                    "foreign key(seance)references SEANCES(ID))")) {
                create4.execute();
            }

        }

    }
}
